# Generated by Django 5.2.7 on 2025-11-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(max_length=5)),
                ('budget', models.IntegerField()),
                ('pic', models.URLField()),
            ],
        ),
    ]
